/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 04142 is Wardrobe 3 Shelf & 4 Drawer Unit 400MM White Matte
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Bundle_3_04142: THREE.Mesh;
  };
  materials: {
    "Gloss White": THREE.MeshStandardMaterial;
  };
};

export const Model = forwardRef<
  THREE.Mesh,
  ThreeElements["group"] & { onClick?: (event: any) => void }
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/04142.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} onClick={props.onClick}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Bundle_3_04142.geometry}
        material={materials["Gloss White"]}
        position={[-0.016, 0.989, 0.03]}
        rotation={[-Math.PI, 0, -Math.PI]}
        onClick={props.onClick}
      />
    </group>
  );
});

Model.displayName = "Model";

useGLTF.preload("/models/04142.gltf");
