/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 04140 is Wardrobe 6 Shelf Unit 400MM White Matte
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Bundle_1_04140: THREE.Mesh;
  };
  materials: {
    "Gloss White": THREE.MeshStandardMaterial;
  };
};

export const Model = forwardRef<
  THREE.Mesh,
  ThreeElements["group"] & { onClick?: (event: any) => void }
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/04140.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} onClick={props.onClick}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Bundle_1_04140.geometry}
        material={materials["Gloss White"]}
        position={[-0.002, 0.989, 0.009]}
        rotation={[-Math.PI, 0, -Math.PI]}
        onClick={props.onClick}
      />
    </group>
  );
});

Model.displayName = "Model";

useGLTF.preload("/models/04140.gltf");
