/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 04141 is Oak Edging Wardrobe Unit
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    "Bundle_1_04141-Oak_Edging": THREE.Mesh;
    "Bundle_1_04141-Oak": THREE.Mesh;
  };
  materials: {
    Oak_Edging: THREE.MeshStandardMaterial;
    Oak: THREE.MeshStandardMaterial;
  };
};

export const Model = forwardRef<
  THREE.Group,
  ThreeElements["group"] & { onClick?: (event: any) => void }
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/04141.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} onClick={props.onClick}>
      <group position={[-0.023, 0.858, 0.019]}>
        <mesh
          ref={ref}
          castShadow
          receiveShadow
          geometry={nodes["Bundle_1_04141-Oak"].geometry}
          material={materials.Oak}
          onClick={props.onClick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_1_04141-Oak_Edging"].geometry}
          material={materials.Oak_Edging}
          onClick={props.onClick}
        />
      </group>
    </group>
  );
});

Model.displayName = "Model";

useGLTF.preload("/models/04141.gltf");
