/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 01684 is Wardrobe 3 Shelf & 4 Drawer Unit White

import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { GLTF } from "three-stdlib";
import * as THREE from "three";
import { forwardRef, useMemo, useState, useEffect } from "react";
import { useStore } from "../store";

type GLTFResult = GLTF & {
  nodes: {
    "Null1-Gloss_White": THREE.Mesh;
    "Null1-MDF": THREE.Mesh;
  };
  materials: {
    "Gloss White": THREE.MeshStandardMaterial;
    MDF: THREE.MeshStandardMaterial;
  };
};

// Export the component with forwardRef to allow parent components to access the mesh
export const ClassicWardrobe = forwardRef<
  THREE.Mesh,
  ThreeElements["group"] & { onClick?: (event: any) => void }
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/01684.gltf"
  ) as unknown as GLTFResult;

  const getProducts = useStore((state) => state.getProducts);
  const [products, setProducts] = useState<any[]>([]);

  useEffect(() => {
    const loadProducts = async () => {
      try {
        const productsData = await getProducts();
        setProducts(productsData);
      } catch (error) {
        console.error("Failed to load products:", error);
      }
    };
    loadProducts();
  }, [getProducts]);

  // Get real product dimensions from products.json
  const { scaleFactor, yOffset } = useMemo(() => {
    const product = products.find((p) => p.model === "components/W-01684");
    if (!product) {
      console.warn("Product dimensions not found for W-01684");
      return { scaleFactor: 1.0, yOffset: 0 }; // Fallback
    }

    // Calculate scale factor based on actual product dimensions
    // The model should be scaled to match the real-world dimensions
    // Assuming the model is designed for 200cm height, we scale it to match the product height
    const targetHeight = product.height / 100; // Convert cm to R3F units (1 R3F unit = 100cm)
    const modelHeight = 2.0; // Assuming the model is 2 units tall in its original scale
    const scaleFactor = targetHeight / modelHeight;

    // Counteract the built-in Y translation in the GLTF model (0.8250895142555237)
    // to place the wardrobe bottom at Y=0
    const modelBuiltInYOffset = 0.8;
    const yOffset = modelBuiltInYOffset * scaleFactor;

    return { scaleFactor, yOffset };
  }, [products]);

  return (
    <group {...props} dispose={null} onClick={props.onClick}>
      <group scale={scaleFactor} position={[0, yOffset, 0]}>
        <mesh
          ref={ref}
          castShadow
          receiveShadow
          geometry={nodes["Null1-Gloss_White"].geometry}
          material={materials["Gloss White"]}
          onClick={props.onClick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Null1-MDF"].geometry}
          material={materials.MDF}
          onClick={props.onClick}
        />
      </group>
    </group>
  );
});

ClassicWardrobe.displayName = "ClassicWardrobe";

useGLTF.preload("/models/01684.gltf");

// Keep backward compatibility
export const Model = ClassicWardrobe;
