/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 01686 is Wardrobe 6 Shelf Unit White
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_2_01686.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bundle_2_04140.geometry}
        material={materials["Gloss White"]}
        position={[0.016, 0.989, 0.011]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/Bundle_2_01686.gltf");
