/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_7.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf_2.geometry}
        material={materials["Gloss White"]}
        position={[0.048, 0.986, 0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf_1.geometry}
        material={materials["Gloss White"]}
        position={[0.048, 1.367, 0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials["Gloss White"]}
        position={[0.048, 1.703, 0.018]}
      />
      <group position={[0.031, 0.544, -0.094]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Drawer_Glass-Gloss_White"].geometry}
          material={materials["Gloss White"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Drawer_Glass-Glass"].geometry}
          material={materials.Glass}
        />
      </group>
      <group position={[0.031, 0.765, -0.094]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Drawer_Glass_2-Gloss_White"].geometry}
          material={materials["Gloss White"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Drawer_Glass_2-Glass"].geometry}
          material={materials.Glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Drawer_2.geometry}
        material={materials["Gloss White"]}
        position={[0.031, 0.416, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Drawer_1.geometry}
        material={materials["Gloss White"]}
        position={[0.031, 0.197, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wardrobe_Base.geometry}
        material={materials["Gloss White"]}
        position={[0.048, 0.989, 0.015]}
      />
    </group>
  );
}

useGLTF.preload("/Bundle_7.gltf");
