/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_6.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials["Gloss White"]}
        position={[0, 0.565, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf_1.geometry}
        material={materials["Gloss White"]}
        position={[0, 1.708, 0]}
      />
      <group position={[-0.001, 0.095, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wire_Basket_1-White_Mesh"].geometry}
          material={materials["White Mesh"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wire_Basket_1-Gloss_White"].geometry}
          material={materials["Gloss White"]}
        />
      </group>
      <group position={[-0.001, 0.313, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wire_Basket_2-White_Mesh"].geometry}
          material={materials["White Mesh"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wire_Basket_2-Gloss_White"].geometry}
          material={materials["Gloss White"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Metal_Hanger_Bar.geometry}
        material={materials.Metal}
        position={[0, 1.618, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wardrobe_Base.geometry}
        material={materials["Gloss White"]}
        position={[0, 0.989, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Bundle_6.gltf");
