/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_5.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials["Gloss White"]}
        position={[0, 0.565, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf_1.geometry}
        material={materials["Gloss White"]}
        position={[0, 1.708, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Metal_Hanger_Bar.geometry}
        material={materials.Metal}
        position={[0, 1.618, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wardrobe_Base.geometry}
        material={materials["Gloss White"]}
        position={[0, 0.989, 0]}
      />
      <group position={[-0.01, 0.186, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack-White_metal"].geometry}
          material={materials["White metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack-White_Mesh"].geometry}
          material={materials["White Mesh"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack-White_metal_1"].geometry}
          material={materials["White metal"]}
        />
      </group>
      <group position={[-0.01, 0.399, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack1-White_metal"].geometry}
          material={materials["White metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack1-White_Mesh"].geometry}
          material={materials["White Mesh"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Shoe_Rack1-White_metal_1"].geometry}
          material={materials["White metal"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bundle_5.gltf");
