/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 01685 is Wardrobe 1 Hang Rail 2 Shelf Unit White
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    "Bundle_3_01685-Metal": THREE.Mesh;
    "Bundle_3_01685-Gloss_White": THREE.Mesh;
  };
  materials: {
    Metal: THREE.MeshStandardMaterial;
    "Gloss White": THREE.MeshStandardMaterial;
  };
};

export const Model = forwardRef<
  THREE.Group,
  ThreeElements["group"] & { onClick?: (event: any) => void }
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/01685.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} onClick={props.onClick}>
      <group position={[0.016, 0.989, 0.011]}>
        <mesh
          ref={ref}
          castShadow
          receiveShadow
          geometry={nodes["Bundle_3_01685-Gloss_White"].geometry}
          material={materials["Gloss White"]}
          onClick={props.onClick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_3_01685-Metal"].geometry}
          material={materials.Metal}
          onClick={props.onClick}
        />
      </group>
    </group>
  );
});

Model.displayName = "Model";

useGLTF.preload("/models/01685.gltf");
