/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// 01685 is Wardrobe 1 Hang Rail 2 Shelf Unit White
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_3_01685.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0.016, 0.989, 0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_3_01685-Metal"].geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_3_01685-Gloss_White"].geometry}
          material={materials["Gloss White"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bundle_3_01685.gltf");
