/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bundle_2_04141.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.023, 0.858, 0.019]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_1_04141-Oak_Edging"].geometry}
          material={materials.Oak_Edging}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_1_04141-Oak"].geometry}
          material={materials.Oak}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bundle_2_04141.gltf");
