/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/04143.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.013, 0.989, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_4_04143-Oak_Edging"].geometry}
          material={materials.Oak_Edging}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_4_04143-Oak"].geometry}
          material={materials.Oak}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/04143.gltf");
