/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/04145.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.01, 0.989, 0.029]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_6_04145-Oak_Edging"].geometry}
          material={materials.Oak_Edging}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Bundle_6_04145-Oak"].geometry}
          material={materials.Oak}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/04145.gltf");
